### ISSUE TITLE
DLT messages time stamps

### ISSUE THREAD

**Issue by danashevskiy** [bmwcarit/python-dlt#19]
Is there anyway to add time data to dlt messages in `python-dlt`? As I understood `libdlt` doesn't support this functionality. And for example time data in `DLT viewer` is implemented on application site.

**Comment by aigarius** [comment]
There are two fields in the DLTMessage object - tmsp and storage_timestamp. First is communicated from the device and is seconds since the bootup of the device (so it resets to zero on each reboot) and the second is recorded at the moment when dlt-recieve (or pydlt-recieve) receives the message from the device and saves it into the DLT file. This is absolute time in the timezone of the receiving worker PC. Same as in DLT Viewer.

**Comment by danashevskiy** [comment]
@aigarius thanks for a fast reply. Could you please tell is there a way to get them using `DLTBroker` class?

**Comment by aigarius** [comment]
When you are receiving a DLT message from DLTBroker, it should already have both properties set.
